from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_MAX_DEPTH = 8

IGNORED_DIR_NAMES = {
    ".git",
    ".idea",
    ".venv",
    ".venv312",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
}

STOP_DESCENT_NAMES = {
    "runs",
    "notebook_artifacts",
    "archived_post_phase_b",
}

DIRECTORY_PURPOSES = {
    ".": "Thesis workspace for hourly day-ahead electricity price forecasting, including data preparation, benchmarking, and reporting.",
    "data": "Data lake for raw source files, cleaned datasets, and forecasting outputs.",
    "data/00_Raw": "Raw source files collected from ENTSO-E and related market-data pulls before cleaning.",
    "data/00_Raw/DA_Prices": "Raw day-ahead price source files by market/country.",
    "data/00_Raw/ENTSOE": "Raw ENTSO-E exports and market-related source families used for broader energy-system features.",
    "data/00_Raw/Load": "Raw actual-load, day-ahead load forecast, and week-ahead load forecast inputs.",
    "data/00_Raw/RES_Generation_Forecast": "Raw renewable and generation-related source files, including forecasts and capacity families.",
    "data/01_cleaned": "Cleaned, analysis-ready datasets produced by the project's data pipelines.",
    "data/01_cleaned/Day_ahead_prices": "Cleaned day-ahead price datasets plus diagnostics and plots.",
    "data/01_cleaned/Day_ahead_prices/DA_prices": "Final cleaned day-ahead price tables split by resolution and aggregation level.",
    "data/01_cleaned/Day_ahead_prices/diagnostics": "Cleaning diagnostics for duplicates, gaps, and parsing issues in day-ahead prices.",
    "data/01_cleaned/Day_ahead_prices/plots": "Cleaning-stage plots such as yearly views and outlier-week visualizations.",
    "data/01_cleaned/Generation": "Cleaned generation-related feature families used for feature engineering and audits.",
    "data/01_cleaned/Generation/actual_generation_by_psr": "Cleaned actual generation by production type.",
    "data/01_cleaned/Generation/da_generation_forecast": "Cleaned day-ahead generation forecasts by production type.",
    "data/01_cleaned/Generation/installed_capacity_by_psr": "Cleaned installed-capacity tables by production type.",
    "data/01_cleaned/Load": "Cleaned load-related feature families used for forecasting and diagnostics.",
    "data/01_cleaned/Load/actual_total_load": "Cleaned actual total-load tables.",
    "data/01_cleaned/Load/da_total_load_forecast": "Cleaned day-ahead total-load forecast tables.",
    "data/01_cleaned/Load/week_ahead_total_load_forecast": "Cleaned week-ahead total-load forecast tables.",
    "data/02_Forecasting": "Forecasting outputs and archived benchmark artifacts.",
    "data/02_Forecasting/01_DA_prices": "Outputs for day-ahead price forecasting runs and related archived material.",
    "data/02_Forecasting/01_DA_prices/archive": "Archived outputs from older forecasting layouts kept for traceability.",
    "data/02_Forecasting/01_DA_prices/hourly_da": "Standardized output area for the active hourly day-ahead forecasting workflow.",
    "data/02_Forecasting/01_DA_prices/hourly_da/archived_post_phase_b": "Archived historical run outputs preserved after later pipeline changes.",
    "data/02_Forecasting/01_DA_prices/hourly_da/notebook_artifacts": "Exports generated by notebooks rather than the shared runner scripts.",
    "data/02_Forecasting/01_DA_prices/hourly_da/runs": "Timestamped benchmark runs containing predictions, metrics, timings, and plots.",
    "notebooks": "Interpretation and experiment notebooks; reusable logic should stay in shared modules instead of notebooks.",
    "notebooks/Data": "Notebook work organized around data preparation, forecasting experiments, and interpretation.",
    "notebooks/Data/02_Forecasting": "Forecasting-focused notebooks grouped by thesis workflow stage.",
    "notebooks/Data/02_Forecasting/01_DA_prices": "Main notebook workspace for hourly day-ahead price experiments and interpretation.",
    "notebooks/Data/02_Forecasting/01_DA_prices/archive_pre_fs_order_layout": "Archived notebooks from an older feature-set ordering layout.",
    "notebooks/Data/02_Forecasting/01_DA_prices/archive_pre_standardized_pipeline": "Archived notebooks from before the standardized forecasting pipeline.",
    "notebooks/Data/02_Forecasting/01_DA_prices/archive_retired_models": "Archived notebooks for retired or superseded model families.",
    "notebooks/Data/02_Forecasting/01_DA_prices/cleaning_DA_prices": "Notebook workspace focused on day-ahead price cleaning and inspection.",
    "scripts": "Reusable Python scripts and modules for imports, cleaning, forecasting, and reporting.",
    "scripts/Data": "Code grouped by the project's data workflow stages.",
    "scripts/Data/00_data_imports": "Raw-data acquisition helpers.",
    "scripts/Data/01_cleaning": "Cleaning pipelines that convert raw source files into standardized cleaned datasets.",
    "scripts/Data/02_Forecasting": "Forecasting runners and reusable forecasting package code.",
    "scripts/Data/02_Forecasting/01_DA_prices": "Main hourly day-ahead forecasting runner folder with benchmark entrypoints and docs.",
    "scripts/Data/02_Forecasting/01_DA_prices/archive": "Archived forecasting code kept for historical reference.",
    "scripts/Data/02_Forecasting/01_DA_prices/archive/legacy_local_origin_scaffold": "Legacy scaffold from an older local-origin forecasting layout.",
    "scripts/Data/02_Forecasting/01_DA_prices/archive/retired_models": "Retired model implementations and old benchmark runners.",
    "scripts/Data/02_Forecasting/01_DA_prices/docs": "Documentation and notes for the forecasting pipeline.",
    "scripts/Data/02_Forecasting/01_DA_prices/hourly_da": "Reusable hourly day-ahead forecasting package shared across benchmark runners.",
    "scripts/Data/02_Forecasting/01_DA_prices/hourly_da/core": "Core shared logic for scheduling, evaluation, metrics, storage, features, and monitoring.",
    "scripts/Data/02_Forecasting/01_DA_prices/hourly_da/models": "Model-specific implementations plugged into the shared evaluation pipeline.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Print a concise overview of the project's directories and their roles."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Project root to inspect. Defaults to the repository root.",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=DEFAULT_MAX_DEPTH,
        help="Maximum directory depth to include automatically. Described paths are always included.",
    )
    return parser.parse_args()


def normalize_rel_path(path: Path) -> str:
    if path == Path("."):
        return "."
    return path.as_posix()


def has_described_descendant(rel_path: str) -> bool:
    prefix = f"{rel_path}/"
    return any(path.startswith(prefix) for path in DIRECTORY_PURPOSES)


def describe_directory(path: Path, rel_path: str) -> str:
    if rel_path in DIRECTORY_PURPOSES:
        return DIRECTORY_PURPOSES[rel_path]

    name = path.name.lower()

    fallback_messages = {
        "archive": "Archived historical material kept for traceability and comparison.",
        "docs": "Documentation and supporting notes for this part of the project.",
        "runs": "Timestamped run outputs with predictions, metrics, timings, and plots.",
        "notebook_artifacts": "Exports generated from notebooks.",
        "plots": "Generated figures and visual diagnostics.",
        "diagnostics": "Quality checks, audits, and issue-tracking outputs.",
        "parsed": "Parsed intermediate tables before the final cleaned outputs.",
        "hourly": "Hourly-resolution data outputs used by the active thesis workflow.",
        "quarterly": "Quarter-hourly outputs kept for reference outside the active thesis scope.",
        "aggregated": "Aggregated tables combined from lower-level source data.",
        "core": "Shared pipeline utilities used across multiple models and runners.",
        "models": "Model-specific implementations connected to the shared evaluation pipeline.",
    }
    if name in fallback_messages:
        return fallback_messages[name]

    if name.startswith("archive"):
        return "Archived historical material kept for traceability and comparison."

    if any(path.glob("*.ipynb")):
        return "Notebook workspace for exploratory analysis and interpretation."

    if any(path.glob("run_*.py")):
        return "Runnable entrypoints for data or forecasting workflows."

    return "Container directory for related project assets and submodules."


def collect_directories(root: Path, max_depth: int) -> list[tuple[int, str, Path]]:
    directories: list[tuple[int, str, Path]] = []

    def walk(path: Path, rel_path: Path) -> None:
        rel_str = normalize_rel_path(rel_path)
        depth = 0 if rel_str == "." else len(rel_path.parts)

        is_described = rel_str in DIRECTORY_PURPOSES
        if depth > max_depth and not is_described and not has_described_descendant(rel_str):
            return

        if rel_str == "." or depth <= max_depth or is_described:
            directories.append((depth, rel_str, path))

        if path.name in STOP_DESCENT_NAMES:
            return

        child_dirs = sorted(
            (
                child
                for child in path.iterdir()
                if child.is_dir() and child.name not in IGNORED_DIR_NAMES
            ),
            key=lambda child: child.name.lower(),
        )

        for child in child_dirs:
            walk(child, child.relative_to(root))

    walk(root, Path("."))
    return directories


def render_report(root: Path, max_depth: int) -> str:
    lines = [
        f"Project directory overview for {root}",
        f"Included depth: {max_depth} (plus explicitly described deeper paths)",
        "",
    ]

    for depth, rel_str, path in collect_directories(root, max_depth):
        indent = "  " * depth
        lines.append(f"{indent}- {rel_str}: {describe_directory(path, rel_str)}")

    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    root = args.root.resolve()

    if not root.exists():
        raise SystemExit(f"Root path does not exist: {root}")

    print(render_report(root, args.max_depth))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
